### ISSUE TITLE
Creating a resumable upload from chunks

### ISSUE THREAD

**Issue by Cdik** [googleapis/gcs-resumable-upload#132]
Hi @JustinBeckwith ,

I'm starting being nuts!!
After [this comment](https://github.com/googleapis/nodejs-storage/issues/232#issuecomment-436189695) you might have read, I have been redirected to your Git repo but don't get how to use `gcs-resumable-uplaod` with bytes when you don't have direct access to the file!

Here's the use case:
- I'm sending files(images) as base64 bytes from my mobile app to one of my api endpoint (hosted on Firebase Hosting)
- Because Firebase requests are limited to 10MB, if the file size is less than 10MB, I send the entire file bytes and do a regular upload using [`file.save()`](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/File#save)
```js
const options = {
    contentType: "image/jpeg",
    offset: 0,
    resumable: false,
};
      
const buffer = new Buffer(req.body.media_data, 'base64');
      
return file.save(buffer, options, async (error, success) => {
    if (!error) {
        return res.status(200).json({
            status: 200,
            data: success
         }).send();
    } else {
         return res.status(500).json({
            status: -1,
            data: `Error while saving data: ${error}`
         }).send();
    }
});
```
_Until this point, everything is okay and I'm able to upload "small" files to my GCS_
- If the file size is larger than 10MB, my mobile app "cuts" the file to send chunks of maximum 10MB.
- When I retrieve a chunk on the api endpoint, I tried two methods:
    1. - using `file.save()` as the documentation says _"Resumable uploads are automatically enabled and must be shut off explicitly by setting options.resumable to false"_  I then use the same method as above with `options.resumable=true` until I receive the last chunk from the mobile app.
    2. - using `file.createResumableStream()` + `file.createWriteStream()`: createWriteStream will then receive an additional `options.uri` from createResumableStream.

- With both methods I get errors messages:
    1. - first method returns _`Resumable uploads require write access to the $HOME directory. Through config-store, some metadata is stored. By default, if the directory is not writable, we will fall back to a simple upload. However, if you explicitly request a resumable upload, and we cannot write to the config directory, we will return a ResumableUploadError.`_
    2. - second method returns _`Error: Upload failed`_

What is wrong? I wanted to try your `gcs-resumable-upload` but how to use it with chunks? Because I don't have direct access to the file, bytes are coming from my mobile app.

**Comment by Cdik** [comment]
Hi @gcochard ,
Thanks for you answer, I went for the second approach (more or less) and it's working 👍 

Here's the step-by-step process if someone is interested:
1. -> mobile app sends first chunk to api endpoint
2. -> backend creates a folder in GCS, saves the first chunk and names it by a timestamp (using [file.save() method](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/File#save))
3. -> backend returns the folder path to the mobile app
4. -> mobile app sends the second chunk AND the folder path
5. -> backend saves the second chunk and names it by a new timestamp at `folder_path`
6. -> ... repeat steps 4 and 5 with all the chunks until the last chunk
7. -> backend saves the last chunk
8. -> backend waits a _"couple of seconds"_ for the last chunk to be available in the storage bucket
9. -> backend retrieves all files at `folder_path` (using [bucket.getFiles() method](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/Bucket#getFiles))
10. -> backend combines all files into one new file (using [bucket.combine() method](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/Bucket#combine))
11. -> backend deletes all the chunks. (using [bucket.deleteFiles() method](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/Bucket#deleteFiles))

**Important:**
- When the mobile app sends a chunk, it needs to send `last_chunk=true/false` at the same time so the backend knows when to retrieve and combine the chunks (also useful if you want to handle errors and ask the mobile app to send a specific chunk again).
- Naming the chunks by a timestamp (or something that can identify the position of each chunk) is needed because when you retrieve the files you get them by alphabetical order and combining them together may lead into a corrupted file if the chunks are in the wrong order.
- You need somehow to wait between the last chunk saved and retrieval of all the files otherwise the last chunk is not yet available in GCS and you will miss it while combining.

Note:
- I doubt it is the best way of doing it because of the number of requests it does to GCS (which probably generates payable queries).
- For the waiting time _(see step 8)_, I'm currently using a regular setTimeout() method of 10sec but it's not reliable at all as it depends on the chunk size and on GCS to make the chunk available in the bucket. I haven't dig into that yet but I guess the best would probably be to do something like a loop with last_chunk[.exists()](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/File#exists) and retrieve all files when `true`. (?)

It's working pretty well so far but if someone has any suggestion on the overall process, I'll be glad to hear it.

**Comment by mmcguff** [comment]
Right now I have node.js application where I am trying to use this package for uploading files that are far greater than 10mb and I am running into this same issue of the $home directory being unwriteable.  I am seeing that a some issues were closed on this but I am not really understand what I need to do to implement something that will handle large uploads.  Can someone who solved this issue paste a code sample of how this work here or some guidance on how its suppose to work?  Thanks!

**Comment by stephenplusplus** [comment]
@mmcguff are you using gcs-resumble-upload directly or through @google-cloud/storage? Could you share the versions you're using (Node, and the relevant libraries)? Thanks!

**Comment by mmcguff** [comment]
For my deployment of node, I am using the current LTS which is 10.15.3 at the time of this writing.
Here are the relevant libraries:  

```
 "@google-cloud/storage": "^2.3.4",
 "gcs-resumable-upload": "^0.14.1",
```

My app is currently deployed in heroku but I don't think the problem is tied to the hosting environment.  
Here is example of the error message I get with my current implementation when attempting to deploy:

`ResumableUploadError: A resumable upload could not be performed. The directory, /app/.config, is not writable. You may try another upload, this time setting `options.resumable` to `false`.  `

Thanks for responding so quickly @stephenplusplus Let me know if there is anything else you need.

**Comment by stephenplusplus** [comment]
Thank you! `gcs-resumable-upload` tries to require as little intervention as possible, so by default, it stores a configuration file inside of the host environment's home directory (some more specifics here: https://github.com/googleapis/gcs-resumable-upload/#how-it-works). The configuration file stores some details about the upload so that you never need to worry about how it works. In some cases, that is probably too simple, and you're better off taking over some control. That could be what is necessary here, if you are deployed in an environment that won't allow that configuration file to exist and persist.

A resumable upload is basically these parts:

- Create a resumable upload URI
- PUT data to it
- *uh oh, network down, need to resume the upload*
- GET the size of the file that was saved upstream
- PUT data to it, starting from where the last upload left off
- *PUTs end, upload is done, the complete file is saved*

The first step is where you might need to step in. Instead of starting the upload right away with `file.createWriteStream()`, you could do:

```js
const [uri] = file.createResumableUpload()
```

Then, whenever you need to start the upload (or re-start, if something went wrong):

```js
file.createWriteStream({uri})
```

Pipe data to it as you normally would, and `gcs-resumable-upload` should still figure out all the logistics about where to start from, how to assemble the correct headers, etc.

I hope that helps!

**Comment by mmcguff** [comment]
Is there anyway I can control where that configuration files gets stored so I don't have to store it in the home directory?  if I could do this then I wouldn't have to worry about not being able to get write permission in the heroku $home directory.

**Comment by stephenplusplus** [comment]
That's a good idea! I sent a PR to support it here: https://github.com/googleapis/gcs-resumable-upload/pull/194/files. Then after we release, we can create that option in @google-cloud/nodejs-storage.

**Comment by FullstackJack** [comment]
@Cdik Doesn't your method of saving individual chunks and merging them create many Class A operations vs. just one? If you uploaded a large video with 1000 chunks using this method, you would pay for 1000 Class A inserts, plus whatever a merge costs. So instead of paying $0.000005 in operation fees, you'd be paying for $0.005 (or half a penny). Multiply this by say 100k uploads and that's $500 vs. $0.50. Just wanted to point that out.

From the docs, "A completed resumable upload is considered one Class A operation."

https://cloud.google.com/storage/docs/resumable-uploads

**Comment by Cdik** [comment]
@FullstackJack . Yes, as I wrote, it does create multiple billing ops. We changed our solution since then and only use one resumable upload operation :)

**Comment by darkmakukudo** [comment]
@Cdik in your updated solution, I'm assuming you no longer upload the file in chunk right?
