### ISSUE TITLE
Reasons behind gcs-resumable-upload deprecation and recommended alternatives?

### ISSUE THREAD

**Issue by jthomasprogrammer** [googleapis/gcs-resumable-upload#533]
I was about to incorporate this library into some code, so I was wondering if it was possible to share the reasons behind this library's deprecation?

A recommended alternative would also be helpful (if there is a leading contender).

**Comment by ddelgrosso1** [comment]
Hi @jthomasprogrammer thank you for the question. Before January of 2022 the Google Cloud Storage library was the largest consumer of GCS Resumable Upload. Due to the difficulty in implementing breaking / API changes the Cloud Storage team made the decision to internalize resumable upload functionality into that library. As a result the usage of this library has been dwindling.

We also examined the health of the projects dependent on GCS Resumable Upload and determined that the number was small and many were no longer actively being maintained. All of this combined led us to the decision to move away from supporting GCS Resumable Upload as an independent library. Our recommendation currently would be to use the Google Cloud Storage library which has resumable upload functionality.

With all of that said, support for this library will continue until November 1, 2023.

**Comment by jthomasprogrammer** [comment]
Gotcha, thank you @ddelgrosso1.
