### ISSUE TITLE
Allow passing in query parameters when creating the upload URI

### ISSUE THREAD

**Issue by galniv** [googleapis/gcs-resumable-upload#7]
The GCS API supports a number of query parameters when creating a resumable upload URI (https://cloud.google.com/storage/docs/json_api/v1/objects/insert#request). The most valuable one for my use case is the ability to set one of the predefined ACL strings -- I have not been able to find a way to pass this parameter as part of the metadata the request body.

It would be great if this module (and by extension, [gcloud](https://github.com/GoogleCloudPlatform/gcloud-node)) supported a way to pass these in. My suggestion would either be to add a new `queryParameters` object to the config, or to piggyback onto the existing `cfg.metadata` object -- if `cfg.metadata.queryParameters` exists, extract the parameters from it.

The first has the advantage of being cleaner, while the second has the advantage of working out-of-the-box with the existing gcloud code, since the `metadata` object is passed to this module as-is.

If you consider this a valuable addition to the module, I'd be happy to submit a pull request for whichever method makes more sense to you.

**Comment by stephenplusplus** [comment]
It would be nice to build this into `gcloud` as well, but it would probably force some bigger changes, maybe:

```js
file.createWriteStream({
  gzip: true,
  query: {
    predefinedAcl: 'publicRead'
  },
  metadata: {
    contentType: 'image/jpeg'
  }
});
```

Or, to stick to a familiar pattern for those who have used the `request` library before:

```js
file.createWriteStream({
  gzip: true,
  request: {
    qs: {
      predefinedAcl: 'publicRead'
    },
    json: {
      contentType: 'image/jpeg'
    }
  }
});
```

@callmehiphop -- any ideas on a way we can implement this? We have [Interceptors](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/gcloud), but they won't work here, since resumable file uploads are run through this module.

Is there a smarter way to allow method-level, complete request override access in a way that doesn't trash our API (in terms of breaking changes or just verboseness?)

**Comment by stephenplusplus** [comment]
A PR is here! Finally! #275
